---
- name: Configuring tomcat using child playbooks and host scope varibales
  hosts: all
  tasks:
    - name: Call multiple child playbooks
      include_tasks: "{{item}}"
      with_items:
        - install_tomcat.yml
        - copy_tomcat.yml
        - change_port.yml
        - restart_tomcat.yml
        - pause.yml
        - check_tomcat_response.yml
...
