---
- name: Create users and copy files into users home dir
  hosts: all
  tasks:
    - name: Create multiple users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: Anu,b: intelliqit,c: /tmp/Anu}
        - {a: Ravi,b: intelliqit,c: /home/Ravi}
    - name: copy files into users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
        owner: "{{item.c}}"
        group: "{{item.d}}"
        mode: "{{item.e}}"
      with_items:
        - {a: /etc/passwd,b: /tmp/Anu,c: Anu,d: Ravi,e: 773}
        - {a: /etc/group,b: /home/Ravi,c: Ravi,d: Anu,e: 700}
...
