---
- name: Configure apache2 on Ubuntu and httpd on RHEL servers
  hosts: all
  tasks:
    - name: Install apache2 on Ubuntu servers
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on RHEL servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file
      copy:
        content: "Intelliq"
        dest: /var/www/html/index.html
    - name: Restart apache2 on Ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on RHEL servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check respone on apache2/httpd on all servers
      uri:
        url: "{{item}}"
      with_items:
          - http://172.31.46.133
          - http://172.31.62.96
          - http://172.31.48.12
          - http://172.31.30.198







