---
- name: Using hsot scope varaibles
  hosts: 172.31.30.198
  tasks:
   - name: Create user
     user:
       name: "{{a}}"
       password: "{{b}}"
       uid: "{{c}}"
       home: "{{d}}"
       shell: "{{e}}"
       comment: "{{f}}"
